name: Node.js

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Build & Test App
        run: |
          pnpm install
          pnpm test